application:
  port: 9010
  host: "http://localhost:9010/"
  db:
    url: "user=otten password=password host=localhost port=5432 dbname=datangya sslmode=disable TimeZone=Asia/Jakarta"

majalah:
  host: "https://majalah.ottencoffee.co.id/index.php/wp-json/wp/v2/"
  